// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.DatabaseContext;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(PMSDatabaseContext))]
    partial class PMSDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEnded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalInsuranceScheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "588cc79d-bfba-4063-a577-a08a19ff3fba",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "4b55e0a7-acca-40f2-9785-95d38292817e",
                            DateEnded = new DateTime(2024, 7, 26, 18, 54, 41, 395, DateTimeKind.Local).AddTicks(6885),
                            DateOfBirth = new DateTime(2024, 7, 26, 18, 54, 41, 395, DateTimeKind.Local).AddTicks(6876),
                            DateRegistered = new DateTime(2024, 7, 26, 18, 54, 41, 395, DateTimeKind.Local).AddTicks(6884),
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            Gender = "",
                            ImagePath = "",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NationalInsuranceScheme = "",
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK9G/uzUyBgNM50dbJzsosBrz9O1DZPeWZNiTYe0NXQPybeuekrE122NZjz7F2drVQ==",
                            PhoneNumberConfirmed = false,
                            Role = "",
                            SecurityStamp = "19f68cc1-35fb-458a-9b47-0c12fe003468",
                            TaxRegistrationNumber = "",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "4cb8218a-f54a-472f-84db-275ff92a659f",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "a81c033a-1ef2-4b39-90b6-9e26b10bd2cd",
                            DateEnded = new DateTime(2024, 7, 26, 18, 54, 41, 434, DateTimeKind.Local).AddTicks(9213),
                            DateOfBirth = new DateTime(2024, 7, 26, 18, 54, 41, 434, DateTimeKind.Local).AddTicks(9207),
                            DateRegistered = new DateTime(2024, 7, 26, 18, 54, 41, 434, DateTimeKind.Local).AddTicks(9213),
                            Email = "appraiser@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Appraiser",
                            Gender = "",
                            ImagePath = "",
                            LastName = "Appraiser",
                            LockoutEnabled = false,
                            NationalInsuranceScheme = "",
                            NormalizedEmail = "APPRAISER@LOCALHOST.COM",
                            NormalizedUserName = "APPRAISER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED02h49AQw+hNl1u5YatxJszNbY4tIY8RR25j67cIW/oQid98rIrJdvjNQn7fH1kWw==",
                            PhoneNumberConfirmed = false,
                            Role = "",
                            SecurityStamp = "bde2e99d-f15d-430e-a517-8337ae5d108a",
                            TaxRegistrationNumber = "",
                            TwoFactorEnabled = false,
                            UserName = "appraiser@localhost.com"
                        },
                        new
                        {
                            Id = "89d67a78-bd8e-4e72-93dc-602de068282a",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "eace97ee-b1dd-4fdc-b50f-c975fd149e77",
                            DateEnded = new DateTime(2024, 7, 26, 18, 54, 41, 475, DateTimeKind.Local).AddTicks(4480),
                            DateOfBirth = new DateTime(2024, 7, 26, 18, 54, 41, 475, DateTimeKind.Local).AddTicks(4469),
                            DateRegistered = new DateTime(2024, 7, 26, 18, 54, 41, 475, DateTimeKind.Local).AddTicks(4480),
                            Email = "client@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Client",
                            Gender = "",
                            ImagePath = "",
                            LastName = "Client",
                            LockoutEnabled = false,
                            NationalInsuranceScheme = "",
                            NormalizedEmail = "CLIENT@LOCALHOST.COM",
                            NormalizedUserName = "CLIENT@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKRZTLWpT24PMcaiyRDLIVDRQ10cEXugKSuRu6LpM741gu4A7tjFlaD2Mj4FCUqOqg==",
                            PhoneNumberConfirmed = false,
                            Role = "",
                            SecurityStamp = "e1d933c3-532f-4f2e-9f0a-e701dc680774",
                            TaxRegistrationNumber = "",
                            TwoFactorEnabled = false,
                            UserName = "client@localhost.com"
                        });
                });

            modelBuilder.Entity("Domain.CheckBox.PurposeValuation.FormPurposeOfValuationItem", b =>
                {
                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<int>("PurposeOfValuationItemId")
                        .HasColumnType("int");

                    b.HasKey("FormId", "PurposeOfValuationItemId");

                    b.HasIndex("PurposeOfValuationItemId");

                    b.ToTable("ServiceRequestFormPurposeOfValuationItems");
                });

            modelBuilder.Entity("Domain.CheckBox.PurposeValuation.PurposeOfValuationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PurposeOfValuationItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsChecked = false,
                            Title = "Market Value"
                        },
                        new
                        {
                            Id = 2,
                            IsChecked = false,
                            Title = "Sale"
                        },
                        new
                        {
                            Id = 3,
                            IsChecked = false,
                            Title = "Purchase"
                        },
                        new
                        {
                            Id = 4,
                            IsChecked = false,
                            Title = "Mortgage"
                        },
                        new
                        {
                            Id = 5,
                            IsChecked = false,
                            Title = "Insurance"
                        },
                        new
                        {
                            Id = 6,
                            IsChecked = false,
                            Title = "Probate"
                        });
                });

            modelBuilder.Entity("Domain.CheckBox.ServiceRequest.FormServiceRequestItem", b =>
                {
                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceRequestItemId")
                        .HasColumnType("int");

                    b.HasKey("FormId", "ServiceRequestItemId");

                    b.HasIndex("ServiceRequestItemId");

                    b.ToTable("ServiceRequestFormServiceRequestItems");
                });

            modelBuilder.Entity("Domain.CheckBox.ServiceRequest.ServiceRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceRequestItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsChecked = false,
                            Title = "VALUATION"
                        },
                        new
                        {
                            Id = 2,
                            IsChecked = false,
                            Title = "LAND SURVEYOR"
                        },
                        new
                        {
                            Id = 3,
                            IsChecked = false,
                            Title = "LEGAL REPRESENTATION"
                        },
                        new
                        {
                            Id = 4,
                            IsChecked = false,
                            Title = "SALES/RENTALS"
                        },
                        new
                        {
                            Id = 5,
                            IsChecked = false,
                            Title = "AUCTION"
                        },
                        new
                        {
                            Id = 6,
                            IsChecked = false,
                            Title = "PROPERTY MANAGEMENT"
                        },
                        new
                        {
                            Id = 7,
                            IsChecked = false,
                            Title = "STRUCTURAL SURVEY"
                        },
                        new
                        {
                            Id = 8,
                            IsChecked = false,
                            Title = "CONSTRUCTION ESTIMATE"
                        },
                        new
                        {
                            Id = 9,
                            IsChecked = false,
                            Title = "GENERAL CONTRACTOR"
                        },
                        new
                        {
                            Id = 10,
                            IsChecked = false,
                            Title = "OTHER"
                        });
                });

            modelBuilder.Entity("Domain.CheckBox.TypeOfProperty.FormTypeOfPropertyItem", b =>
                {
                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfPropertyItemId")
                        .HasColumnType("int");

                    b.HasKey("FormId", "TypeOfPropertyItemId");

                    b.HasIndex("TypeOfPropertyItemId");

                    b.ToTable("ServiceRequesFormTypeOfPropertyItems");
                });

            modelBuilder.Entity("Domain.CheckBox.TypeOfProperty.TypeOfPropertyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfPropertyItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsChecked = false,
                            Title = "Commercial"
                        },
                        new
                        {
                            Id = 2,
                            IsChecked = false,
                            Title = "Residential"
                        },
                        new
                        {
                            Id = 3,
                            IsChecked = false,
                            Title = "Agricultural"
                        },
                        new
                        {
                            Id = 4,
                            IsChecked = false,
                            Title = "Industrial"
                        },
                        new
                        {
                            Id = 5,
                            IsChecked = false,
                            Title = "Vacant Lot"
                        });
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppraiserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppraiserNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApprovedForm")
                        .HasColumnType("datetime2");

                    b.Property<string>("BackOfPropertyImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CancelledForm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFormWasFilledOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FormInProcess")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FromAccepted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FromAssigned")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrontOfProperyImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructionsIssuedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsKeyAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("JobAssignerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeftSideOfPropertImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MarkFromAsCompleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MortgageInstitution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RejectedForm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnFromToAppraiser")
                        .HasColumnType("datetime2");

                    b.Property<string>("RightSideOfPropertyImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryContactFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryContactLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrataPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedFormForApproval")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValuationRequiredBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppraiserId");

                    b.HasIndex("JobAssignerId");

                    b.HasIndex("RegionId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Domain.FormInteractionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppraiserNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Submitted")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("FormId");

                    b.ToTable("FormInteractionLogs");
                });

            modelBuilder.Entity("Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountiesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c8a6b61-43f9-4b7c-ab58-be16c05762b4"),
                            CountiesName = "Surrey",
                            ParishName = "Kingston"
                        },
                        new
                        {
                            Id = new Guid("49ebba81-a529-490c-add9-37046df783f4"),
                            CountiesName = "Surrey",
                            ParishName = "St. Andrew"
                        },
                        new
                        {
                            Id = new Guid("67a014d7-dbc6-40e7-a5b8-8eb12edfd68b"),
                            CountiesName = "Surrey",
                            ParishName = "Portland"
                        },
                        new
                        {
                            Id = new Guid("5d3bb8cd-bdb8-4752-9a53-b656e2543481"),
                            CountiesName = "Surrey",
                            ParishName = "St. Thomas"
                        },
                        new
                        {
                            Id = new Guid("02befa99-5924-4fea-a633-3736e651a2dc"),
                            CountiesName = "Middlesex",
                            ParishName = "St. Catherine"
                        },
                        new
                        {
                            Id = new Guid("05b21946-589d-4195-a632-1f0c554206bb"),
                            CountiesName = "Middlesex",
                            ParishName = "St. Mary"
                        },
                        new
                        {
                            Id = new Guid("cfcfccac-f17b-4ae2-96af-2a4be6b42ba2"),
                            CountiesName = "Middlesex",
                            ParishName = "St. Ann"
                        },
                        new
                        {
                            Id = new Guid("bc5cee4e-a273-4b67-8697-23a489b041fe"),
                            CountiesName = "Middlesex",
                            ParishName = "Manchester"
                        },
                        new
                        {
                            Id = new Guid("1d0844ea-761c-4d00-8446-57cbed7d971a"),
                            CountiesName = "Middlesex",
                            ParishName = "Clarendon"
                        },
                        new
                        {
                            Id = new Guid("5cc3280f-7a72-4fa0-9452-d320bc5dc000"),
                            CountiesName = "Cornwall",
                            ParishName = "Hanover"
                        },
                        new
                        {
                            Id = new Guid("2f020ff7-8b30-48ff-8aff-caf7f18503c2"),
                            CountiesName = "Cornwall",
                            ParishName = "Westmoreland"
                        },
                        new
                        {
                            Id = new Guid("d6b104f3-693f-4c43-8035-21661b61a82b"),
                            CountiesName = "Cornwall",
                            ParishName = "St. James"
                        },
                        new
                        {
                            Id = new Guid("957748c0-ba86-4764-b8c7-a8c0c0bc20c8"),
                            CountiesName = "Cornwall",
                            ParishName = "Trelawny"
                        },
                        new
                        {
                            Id = new Guid("e80ac700-0536-476a-8c7e-467a25a13f55"),
                            CountiesName = "Cornwall",
                            ParishName = "St. Elizabeth"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b3c24a8-fd98-4dd7-8e8e-13b70a7ccc9c",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "1ff8b9a5-91cd-478d-942d-baaca93a4bf9",
                            Name = "Appraiser",
                            NormalizedName = "APPRAISER"
                        },
                        new
                        {
                            Id = "abcf3529-e04c-4fc6-b654-da3f444b3c0c",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "588cc79d-bfba-4063-a577-a08a19ff3fba",
                            RoleId = "0b3c24a8-fd98-4dd7-8e8e-13b70a7ccc9c"
                        },
                        new
                        {
                            UserId = "4cb8218a-f54a-472f-84db-275ff92a659f",
                            RoleId = "1ff8b9a5-91cd-478d-942d-baaca93a4bf9"
                        },
                        new
                        {
                            UserId = "89d67a78-bd8e-4e72-93dc-602de068282a",
                            RoleId = "abcf3529-e04c-4fc6-b654-da3f444b3c0c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.CheckBox.PurposeValuation.FormPurposeOfValuationItem", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("ServiceRequestFormPurposeOfValuationItem")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.CheckBox.PurposeValuation.PurposeOfValuationItem", "PurposeOfValuationItem")
                        .WithMany("FormPurposeOfValuationItem")
                        .HasForeignKey("PurposeOfValuationItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("PurposeOfValuationItem");
                });

            modelBuilder.Entity("Domain.CheckBox.ServiceRequest.FormServiceRequestItem", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("ServiceRequestFormServiceRequestItem")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.CheckBox.ServiceRequest.ServiceRequestItem", "ServiceRequestItem")
                        .WithMany("FormServiceRequestItem")
                        .HasForeignKey("ServiceRequestItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("ServiceRequestItem");
                });

            modelBuilder.Entity("Domain.CheckBox.TypeOfProperty.FormTypeOfPropertyItem", b =>
                {
                    b.HasOne("Domain.Form", "Form")
                        .WithMany("ServiceRequesFormTypeOfPropertyItem")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.CheckBox.TypeOfProperty.TypeOfPropertyItem", "TypeOfPropertyItem")
                        .WithMany("FormTypeOfPropertyItem")
                        .HasForeignKey("TypeOfPropertyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("TypeOfPropertyItem");
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.HasOne("Domain.ApplicationUser", "Appraiser")
                        .WithMany()
                        .HasForeignKey("AppraiserId");

                    b.HasOne("Domain.ApplicationUser", "JobAssigner")
                        .WithMany()
                        .HasForeignKey("JobAssignerId");

                    b.HasOne("Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.Navigation("Appraiser");

                    b.Navigation("JobAssigner");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.FormInteractionLog", b =>
                {
                    b.HasOne("Domain.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Domain.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CheckBox.PurposeValuation.PurposeOfValuationItem", b =>
                {
                    b.Navigation("FormPurposeOfValuationItem");
                });

            modelBuilder.Entity("Domain.CheckBox.ServiceRequest.ServiceRequestItem", b =>
                {
                    b.Navigation("FormServiceRequestItem");
                });

            modelBuilder.Entity("Domain.CheckBox.TypeOfProperty.TypeOfPropertyItem", b =>
                {
                    b.Navigation("FormTypeOfPropertyItem");
                });

            modelBuilder.Entity("Domain.Form", b =>
                {
                    b.Navigation("ServiceRequesFormTypeOfPropertyItem");

                    b.Navigation("ServiceRequestFormPurposeOfValuationItem");

                    b.Navigation("ServiceRequestFormServiceRequestItem");
                });
#pragma warning restore 612, 618
        }
    }
}
